package constants

/*
Golf Action
*/
const (
	OP_LOG_ACTION_CREATE             = "CREATE"
	OP_LOG_ACTION_UPDATE             = "UPDATE"
	OP_LOG_ACTION_DELETE             = "DELETE"
	OP_LOG_ACTION_CANCEL             = "CANCEL"
	OP_LOG_ACTION_CANCEL_ALL         = "CANCEL_ALL"
	OP_LOG_ACTION_INPUT_BAG_BOOKING  = "INPUT_BAG_BOOKING"
	OP_LOG_ACTION_BOOK_CADDIE        = "BOOK_CADDIE"
	OP_LOG_ACTION_UPD_BOOK_CADDIE    = "UPD_BOOK_CADDIE"
	OP_LOG_ACTION_MOVE               = "MOVE"
	OP_LOG_ACTION_COPY               = "COPY"
	OP_LOG_ACTION_ADD_MORE           = "ADD_MORE"
	OP_LOG_ACTION_LOCK_TEE           = "LOCK_TEE"
	OP_LOG_ACTION_UNLOCK_TEE         = "UNLOCK_TEE"
	OP_LOG_ACTION_UNLOCK_TURN        = "UNLOCK_TURN"
	OP_LOG_ACTION_CHECK_IN           = "CHECK_IN"
	OP_LOG_ACTION_LOCK_BAG           = "LOCK_BAG"
	OP_LOG_ACTION_ADD_ROUND          = "ADD_ROUND"
	OP_LOG_ACTION_DEL_ROUND          = "DEL_ROUND"
	OP_LOG_ACTION_SPLIT_ROUND        = "SPLIT_ROUND"
	OP_LOG_ACTION_MERGE_ROUND        = "MERGE_ROUND"
	OP_LOG_ACTION_CHANGE_GUEST_STYLE = "CHANGE_GUEST_STYLE"
	OP_LOG_ACTION_CHECK_OUT          = "CHECK_OUT"
	OP_LOG_ACTION_ADD_RENTAL         = "ADD_RENTAL"
	OP_LOG_ACTION_ADD_DRIVING        = "ADD_DRIVING"
	OP_LOG_ACTION_ADD_PROSHOP        = "ADD_PROSHOP"
	OP_LOG_ACTION_ADD_RESTAURANT     = "ADD_RESTAURANT"
	OP_LOG_ACTION_ADD_KIOSK          = "ADD_KIOSK"
	OP_LOG_ACTION_ADD_MINI_B         = "ADD_MINI_B"
)

/*
Module golf
*/
const (
	OP_LOG_MODULE_RECEPTION = "RECEPTION"
	OP_LOG_MODULE_GO        = "GO"
)

/*
Function golf
*/
const (
	OP_LOG_FUNCTION_BOOKING                  = "BOOKING"
	OP_LOG_FUNCTION_UPDATE_BOOKING           = "UPDATE_BOOKING"
	OP_LOG_FUNCTION_CANCEL_ALL_BOOKING       = "CANCEL_ALL_BOOKING"
	OP_LOG_FUNCTION_CANCEL_BOOKING           = "CANCEL_BOOKING"
	OP_LOG_FUNCTION_ADD_BAG_BOOKING          = "ADD_BAG_BOOKING"
	OP_LOG_FUNCTION_ADD_CADDIE_BOOKING       = "ADD_CADDIE_BOOKING"
	OP_LOG_FUNCTION_UPDATE_CADDIE_BOOKING    = "UPDATE_CADDIE_BOOKING"
	OP_LOG_FUNCTION_UPDATE_BAG_BOOKING       = "UPDATE_BAG_BOOKING"
	OP_LOG_FUNCTION_MOVE_BOOKING             = "MOVE_BOOKING"
	OP_LOG_FUNCTION_ADD_MORE_BOOKING         = "ADD_MORE_BOOKING"
	OP_LOG_FUNCTION_ADD_LOCK_TEE             = "ADD_LOCK_TEE"
	OP_LOG_FUNCTION_DELETE_LOCK_TEE          = "DELETE_LOCK_TEE"
	OP_LOG_FUNCTION_WAITTING_LIST            = "WAITTING_LIST"
	OP_LOG_FUNCTION_CHECK_IN                 = "CHECK_IN"
	OP_LOG_FUNCTION_BOOKING_TEE_TIME         = "BOOKING_TEE_TIME"
	OP_LOG_FUNCTION_AGENCY_PAID              = "AGENCY_PAID"
	OP_LOG_FUNCTION_PAYMENT                  = "PAYMENT"
	OP_LOG_FUNCTION_ADD_BOOKING_SERVICE_ITEM = "ADD_BOOKING_SERVICE_ITEM"
)
