package constants

/*
Golf Action
*/
const (
	OP_LOG_ACTION_CREATE             = "CREATE"
	OP_LOG_ACTION_UPDATE             = "UPDATE"
	OP_LOG_ACTION_DELETE             = "DELETE"
	OP_LOG_ACTION_CHECK_IN           = "CHECK_IN"
	OP_LOG_ACTION_LOCK_BAG           = "LOCK_BAG"
	OP_LOG_ACTION_ADD_ROUND          = "ADD_ROUND"
	OP_LOG_ACTION_DEL_ROUND          = "DEL_ROUND"
	OP_LOG_ACTION_SPLIT_ROUND        = "SPLIT_ROUND"
	OP_LOG_ACTION_MERGE_ROUND        = "MERGE_ROUND"
	OP_LOG_ACTION_CHANGE_GUEST_STYLE = "CHANGE_GUEST_STYLE"
	OP_LOG_ACTION_CHECK_OUT          = "CHECK_OUT"
)

/*
Module golf
*/
const (
	OP_LOG_MODULE_RECEPTION = "RECEPTION"
	OP_LOG_MODULE_GO        = "GO"
)

/*
Function golf
*/
const (
	OP_LOG_FUNCTION_BOOKING          = "BOOKING"
	OP_LOG_FUNCTION_WAITTING_LIST    = "WAITTING_LIST"
	OP_LOG_FUNCTION_CHECK_IN         = "CHECK_IN"
	OP_LOG_FUNCTION_BOOKING_TEE_TIME = "BOOKING_TEE_TIME"
	OP_LOG_FUNCTION_AGENCY_PAID      = "AGENCY_PAID"
	OP_LOG_FUNCTION_PAYMENT          = "PAYMENT"
)
