package constants

/*
Golf Action
*/
const (
	OP_LOG_ACTION_CREATE = "CREATE"
	OP_LOG_ACTION_UPDATE = "UPDATE"
	OP_LOG_ACTION_DELETE = "DELETE"
)

/*
Module golf
*/
const (
	OP_LOG_MODULE_RECEPTION = "RECEPTION"
	OP_LOG_MODULE_GO        = "GO"
)

/*
Function golf
*/
const (
	OP_LOG_FUNCTION_BOOKING   = "BOOKING"
	OP_LOG_FUNCTION_CHECKIN   = "CHECK_IN"
	OP_LOG_FUNCTION_LOCK_BAG  = "LOCK_BAG"
	OP_LOG_FUNCTION_ADD_ROUND = "ADD_ROUND"
	OP_LOG_FUNCTION_DEL_ROUND = "DEL_ROUND"
)
