package constants

const CACHE_TIME_QUERY_INFO = 86400 * 30
const CACHE_TIME_QUERY_FOREVER = -1

// const PREFIX_RKEY_ORDER_SOURCE = "DELIVERY_CUSTOMER_ORDER_SOURCE"
// const PREFIX_RKEY_USER_BLACKLIST = "DELIVERY_USER_BLACKLIST"

// JWT Token
const PREFIX_RKEY_JWT = "DELIVERY_CUSTOMER_JWT_TOKEN"
