variables:
  IMAGE_NAME: golf-backend
  LOCAL_REGISTRY: registry.vnpay.vn
  REGISTRY_USERNAME: dvtt

stages:
  # - test ###UnitTest
  - dockerize

# Docker template ########
.dockerize_template: &dockerize
  stage: dockerize
  image: docker:19.03.12
  script:
    - echo "$REGISTRY_PASSWORD" | docker login $LOCAL_REGISTRY --username $REGISTRY_USERNAME --password-stdin
    - echo building docker image ${IMAGE_NAME}:${IMAGE_TAG}
    - docker build --build-arg IMAGE_TAG_ARG=${IMAGE_TAG} -t ${IMAGE_NAME}:${IMAGE_TAG} --file=${DOCKERFILE_NAME} .
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} $LOCAL_REGISTRY/$DEPLOY_ZONE/${IMAGE_NAME}:${IMAGE_TAG}
    - docker push $LOCAL_REGISTRY/$DEPLOY_ZONE/${IMAGE_NAME}:${IMAGE_TAG}
  only:
    refs:
      - tags
  tags: [dvtt]
  allow_failure: false

# On the feature/deploy_dev branch
# Dockerize
dockerize:deploy_dev:
  <<: *dockerize
  variables:
    DEPLOY_ZONE: vnpay
  only:
    refs:
      - feature/deploy_dev
  before_script:
    - export IMAGE_TAG=d-${CI_COMMIT_SHORT_SHA}
    - export DOCKERFILE_NAME=Dockerfile

# On the feature/deploy_test branch
# Dockerize
dockerize:deploy_test:
  <<: *dockerize
  variables:
    DEPLOY_ZONE: vnpay-ocp/dvtt/vn-golf-platform
  only:
    refs:
      - feature/deploy_test
  before_script:
    - export IMAGE_TAG=t-${CI_COMMIT_SHORT_SHA}
    - export DOCKERFILE_NAME=Dockerfile.staging

# On the Master branch
# Dockerize
dockerize:master:
  <<: *dockerize
  variables:
    DEPLOY_ZONE: gd-ocp/dvtt/vn-golf-platform
  before_script:
    - export IMAGE_TAG=m-${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
    - export DOCKERFILE_NAME=Dockerfile.prod