variables:
  PROJECT_NAME: golf-cms
  APP_VERSION: "1.0"

  # ================= GOLF =========================
  GOLF_KUBE_CONFIG_FILE: /home/gitlab-runner/.kube/stag-config

  GOLF_DOCKER_REGISTRY: harbor.vntaxi.net/golf
  GOLF_IMAGE_NAME: $GOLF_DOCKER_REGISTRY/$PROJECT_NAME

  GOLF_K8S_NAMESPACE_DEV: development
  GOLF_VAR_FILE_DEV: "values-dev.yaml"
 
  GOLF_K8S_NAMESPACE_STAGING: staging
  GOLF_VAR_FILE_STAGING: "values-staging.yaml"

  GOLF_K8S_NAMESPACE_PROD: prod
  GOLF_VAR_FILE_PROD: "values-prod.yaml"
  
stages:
  - lint
  - build
  - deploy

# -------------------------------------------------------------------------------
# ----------------- GOLF Development ----------------------------------------------------
# -------------------------------------------------------------------------------
build_dev:
  stage: build
  script:
    - docker build -t $GOLF_IMAGE_NAME:$IMAGE_TAG --file=Dockerfile .
    - docker tag $GOLF_IMAGE_NAME:$IMAGE_TAG $GOLF_IMAGE_NAME:b$APP_VERSION
    - docker push $GOLF_IMAGE_NAME:$IMAGE_TAG
    - docker push $GOLF_IMAGE_NAME:b$APP_VERSION

    # remove old images version keep 2 version
    - docker images | egrep -e "$GOLF_IMAGE_NAME" | tail -n +3 | awk '{print $3}' | xargs -r docker rmi -f
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - dev

deploy_dev:
  stage: deploy
  script:
    - sh deploy.sh ${PROJECT_NAME} ${GOLF_K8S_NAMESPACE_DEV} ${IMAGE_TAG} $GOLF_KUBE_CONFIG_FILE ${GOLF_VAR_FILE_DEV}
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - dev

# -------------------------------------------------------------------------------
# ----------------- GOLF Staging ----------------------------------------------------
# -------------------------------------------------------------------------------
build_staging:
  stage: build
  script:
    - docker build -t $GOLF_IMAGE_NAME:$IMAGE_TAG --file=Dockerfile.staging .
    - docker tag $GOLF_IMAGE_NAME:$IMAGE_TAG $GOLF_IMAGE_NAME:b$APP_VERSION
    - docker push $GOLF_IMAGE_NAME:$IMAGE_TAG
    - docker push $GOLF_IMAGE_NAME:b$APP_VERSION

    # remove old images version keep 2 version
    - docker images | egrep -e "$GOLF_IMAGE_NAME" | tail -n +3 | awk '{print $3}' | xargs -r docker rmi -f
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - master

deploy_staging:
  stage: deploy
  script:
    - sh deploy.sh ${PROJECT_NAME} ${GOLF_K8S_NAMESPACE_STAGING} ${IMAGE_TAG} $GOLF_KUBE_CONFIG_FILE ${GOLF_VAR_FILE_STAGING}
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - master


# -------------------------------------------------------------------------------
# ----------------- GOLF Prod ---------------------------------------------
# -------------------------------------------------------------------------------
build_prod:
  stage: build
  script:
    - docker build -t $GOLF_IMAGE_NAME:$IMAGE_TAG --file=Dockerfile.prod .
    - docker tag $GOLF_IMAGE_NAME:$IMAGE_TAG $GOLF_IMAGE_NAME:b$APP_VERSION
    - docker push $GOLF_IMAGE_NAME:$IMAGE_TAG
    - docker push $GOLF_IMAGE_NAME:b$APP_VERSION

    # remove old images version keep 2 version
    - docker images | egrep -e "$GOLF_IMAGE_NAME" | tail -n +3 | awk '{print $3}' | xargs -r docker rmi -f
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - prod

deploy_prod:
  stage: deploy
  script:
    - sh deploy.sh ${PROJECT_NAME} ${GOLF_K8S_NAMESPACE_PROD} ${IMAGE_TAG} $GOLF_KUBE_CONFIG_FILE ${GOLF_VAR_FILE_PROD}
  variables:
    IMAGE_TAG: b$APP_VERSION.$CI_PIPELINE_ID
  tags:
  - golf
  only:
  - prod
  # when: manual
