apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "golfCms.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "golfCms.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.replicaCount | int }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ include "golfCms.fullname" . }}
    spec:
      imagePullSecrets:
      - name: regcred
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.imageName }}
        image: {{ .Values.dockerRegistry }}/{{ .Values.imageName }}:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: {{ .Values.servicePath }}/
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.servicePath }}/
            port: 4000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
