apiVersion: v1
kind: Service
metadata:
  name: {{ include "golfCms.fullname" . }}
spec:
  selector:
    app: {{ include "golfCms.fullname" . }}
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
    - protocol: TCP
      port: 8000
      targetPort: 8000